### ISSUE TITLE
Computer creation issue(s)

### ISSUE THREAD

**Issue by bapthbrt** [zakird/pyad#100]
There is an issue when you try to create a computer object in Active Directory domain.
It came to me when I tried to find the object I just create with dsa console. I was not able to find it unless I go in the OU container to find it manually.
Then, the join domain operation failed on my server saying that there were no target object in the domain.

So, I looked closely in the object property and it seemed that the object was declared as computer but had the properties of a user (default group "Domain users" or SAMAccountType "805306368").

I finally found a technet article and [this blog page](https://jdhitsolutions.com/blog/writing/1151/create-new-computer-with-adsi/) explaining the issue and how to solve it.
It is basically by design as a computer object is a derivation of a user object. To create correctly a computer object, you need to set the UserAccountControl property of the object with the correct value for a computer (it is by default for a user).

**Comment by bliu199** [comment]
Hi Bapthbrt,

Can you share the codes to update that property of the object please.  Many thanks.

**Comment by bliu199** [comment]
It works after "adcontainer.py" is tuned in the function "create_computer".

**Comment by bapthbrt** [comment]
> It works after "adcontainer.py" is tuned in the function "create_computer".

I'm sorry, I didn't get that.
Could you please explain?

**Comment by bapthbrt** [comment]
> dn="ou=org,ou=Services,dc=mydomain,dc=com"
> ou = pyad.adcontainer.ADContainer.from_dn(dn)
> computer=ou.create_computer("test2")

More like that:
dn="ou=org,ou=Services,dc=mydomain,dc=com"
ou = pyad.adcontainer.ADContainer.from_dn(dn)
computer=ADComputer.create("test2", ou)

ADComputer is inherited from ADContainer
