### ISSUE TITLE
query for non-disabled ad users

### ISSUE THREAD

**Issue by larsuhartmann** [zakird/pyad#102]
Maybe i am just dump or am missing the important point in the pyad doku, but i can't manage to use adquery to select all user objects which are not disabled - in ldap i would do this, usin a filter 
like (!userAccountControl:1.2.840.113556.1.4.803:=2) - is there any way to archieve this with a where_clause?

**Comment by lochyw** [comment]
You should be able to use the useraccountcontrol attribute which gives you the status.
The values are found here: http://www.selfadsi.org/ads-attributes/user-userAccountControl.htm
I then built a mini thing around that to figure out whether the account is disabled or not:
```
q.execute_query(
    attributes = ['distinguishedName','userPrincipalName',
       'objectCategory','objectClass','SamAccountName','Useraccountcontrol'],
    where_clause = f"userPrincipalName='{email}'"
    #base_dn = ""
    )
    for row in q.get_all_results():
        if row["Useraccountcontrol"] is not None and row["SamAccountName"] is not None:
            **if (row["Useraccountcontrol"] / 2 % 2 != 0):**
                disabled = row["SamAccountName"]
                pass
            print(row)
```

Please modify to suit your solution. the magic is bolded tho.

**Comment by larsuhartmann** [comment]
Thanks a lot! It worked :)

**Comment by rainiur** [comment]
> @larsuhartmann You should be able to use the useraccountcontrol attribute which gives you the status.
> The values are found here: http://www.selfadsi.org/ads-attributes/user-userAccountControl.htm
> I then built a mini thing around that to figure out whether the account is disabled or not:
> 
> ```
> q.execute_query(
>     attributes = ['distinguishedName','userPrincipalName',
>        'objectCategory','objectClass','SamAccountName','Useraccountcontrol'],
>     where_clause = f"userPrincipalName='{email}'"
>     #base_dn = ""
>     )
>     for row in q.get_all_results():
>         if row["Useraccountcontrol"] is not None and row["SamAccountName"] is not None:
>             if (row["Useraccountcontrol"] / 2 % 2 != 0): #magic is here <-
>                 disabled = row["SamAccountName"]
>                 pass
>             print(row)
> ```
> 
> Please modify to suit your solution.

This is perfect. Could you show how you would calculate for "Password not Required"?
