### ISSUE TITLE
Version from PyPI is outdated

### ISSUE THREAD

**Issue by IncPlusPlus** [zakird/pyad#105]
get_password_expired() is one of the functions defined in [aduser.py](https://github.com/zakird/pyad/blob/master/pyad/aduser.py#L62). Unfortunately, it was [committed on January 23rd](https://github.com/zakird/pyad/commit/8dc2a5eac9163dfc3831a50adf867b4f860d433f#diff-2495e5922ba5a4fe6ee5be859e9f05f1), one day after the release that was submitted to PyPI. If it wouldn't be a problem, would you mind updating the release on PyPI so that I can properly import pyad with pip instead of using a clone of the repo?

**Comment by zakird** [comment]
I've released 0.6.0.
