### ISSUE TITLE
issue with ADquery with string containing single quote

### ISSUE THREAD

**Issue by zakird** [zakird/pyad#3]
Hi there

I'm working on a piece of software to take group data from a
propriatory system and syncronise that data in to AD groups.

It's all going well and pyad is working well, except where I'm dealing
with users that have apostrophies in their names:

For example Dave O'Connor

I've tried escaping the ' with a \ but it still seems to error.

Is there a different escape character I need to use?

It seems to error on query and create at least with a string with a ' in?

Many thanks
## 

Python 2.7.2 (default, Jun 12 2011, 15:08:59) [MSC v.1500 32 bit
(Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.

> > > from pyad import pyad
> > > from pyad import adquery
> > > q = adquery.ADQuery()
> > > query = "cn = 'O\'Connell'"
> > > q.execute_query(where_clause = query)
> > > Traceback (most recent call last):
> > >  File "<stdin>", line 1, in <module>
> > >  File "c:\python27\lib\site-packages\pyad-0.4.10-py2.7.egg\pyad\adquery.py",
> > > line 23, in execute_query
> > >  File "<COMObject ADODB.Connection>", line 3, in Execute
> > >  File "c:\python27\lib\site-packages\win32com\client\dynamic.py",
> > > line 276, in _ApplyTypes_
> > >    result = self._oleobj_.InvokeTypes(_(dispid, LCID, wFlags,
> > > retType, argTypes) + args)
> > > pywintypes.com_error: (-2147352567, 'Exception occurred.', (0,
> > > u'Provider', u'One or more errors occurred during processing of
> > > command.', None, 1240640, -2147217900), None)
> > > query = "cn = O'Connell"
> > > q.execute_query(where_clause = query)
> > > Traceback (most recent call last):
> > >  File "<stdin>", line 1, in <module>
> > >  File "c:\python27\lib\site-packages\pyad-0.4.10-py2.7.egg\pyad\adquery.py",
> > > line 23, in execute_query
> > >  File "<COMObject ADODB.Connection>", line 3, in Execute
> > >  File "c:\python27\lib\site-packages\win32com\client\dynamic.py",
> > > line 276, in _ApplyTypes_
> > >    result = self._oleobj_.InvokeTypes(_(dispid, LCID, wFlags,
> > > retType, argTypes) + args)
> > > pywintypes.com_error: (-2147352567, 'Exception occurred.', (0,
> > > u'Provider', u'One or more errors occurred during processing of
> > > command.', None, 1240640, -2147217900), None)

**Comment by Ds3c-ctf-team** [comment]
[``](

> **_**# 

- [ ] [1. ](`url`)

- 1. url

**_**

)
