### ISSUE TITLE
Unable to import any module

### ISSUE THREAD

**Issue by paulparas** [zakird/pyad#37]
Hi Zakir

I've just started python, I'm installing the pyad module using setup.py -install method and it says installed successfully and .egg file is also copied to site-packages folder.

But when I run this "from pyad import aduser" it throws error :
Traceback (most recent call last):
  File "pyad.py", line 1, in <module>
    from pyad import aduser
  File "C:\Users\Paul\Documents\Python\pyad.py", line 1, in <module>
    from pyad import aduser
ImportError: cannot import name aduser

Can you help me out on this.

Thank You!

**Comment by zakird** [comment]
This is because aduser is a module not a class. If you just want the user
class, you need to do

from pyad.aduser import ADUser
