### ISSUE TITLE
CN vs sAMAccountName in create_user

### ISSUE THREAD

**Issue by zerok** [zakird/pyad#44]
Currently adcontainer.create_user sets both the common name and the sAMAccountName to the same value. These fields have different length restrictions with the latter most often being limited to 20 chars. Would it make sense to add another optional argument to the create_user function that contains the value for sAMAccountName and uses the name if not provided?

We currently run into the issue that we use the CN for the complete name of a person, which quite often is not a viable option for the sAMAccountName. For this reason we currently provide a fitting login in the optional_attributes but the are only used after the first attempt has been made to save the user.

This results in errors like this:

```
   ...
    optional_attributes=add_attr)
  File "C:\srv\proj.env\lib\site-packages\pyad\adcontainer.py", line 46, in create_user
    pyadutils.pass_up_com_exception(e)
  File "C:\srv\proj.env\lib\site-packages\pyad\pyadutils.py", line 52, in pass_up_com_exception
    raise WIN32_ERRORS.get(info['error_num'], win32Exception)(error_info=info, additional_info=additional_info)
win32Exception: 0x8007001f: A device attached to the system is not functioning.
```

Not the most useful error message by the underlying system ;-)

**Comment by zakird** [comment]
I'd be fine with adding that.

**Comment by zerok** [comment]
Thanks :) I'll prepare a pull request ASAP.
