### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by Vince-AC** [zakird/pyad#47]
I just ran "futurize" on this package and after some very brief testing it appears to make everything both Python 2 and Python 3 compatible.  Are you interested in Python 3 support for this package as well?

**Comment by zakird** [comment]
I think would be great to add Python3 support. I have never had the time to
look into it, but would happy merging something in if someone can test.

**Comment by Vince-AC** [comment]
Great. I made some changes and did a pull request. 







On Thu, Jan 14, 2016 at 9:43 AM -0800, "Zakir Durumeric" <notifications@github.com> wrote:










I think would be great to add Python3 support. I have never had the time to

look into it, but would happy merging something in if someone can test.

**Comment by zakird** [comment]
I haven't see a pull request come through.

**Comment by Vince-AC** [comment]
I just sent it. 

Vincent Merlino




On Thu, Jan 14, 2016 at 6:56 PM -0800, "Zakir Durumeric" <notifications@github.com> wrote:












I haven't see a pull request come through.

**Comment by apekatten** [comment]
+1 for Python3 support!
