### ISSUE TITLE
Want to manipulate  windows AD remotely on linux

### ISSUE THREAD

**Issue by you-n-g** [zakird/pyad#64]
Hi, 
Nice to find a python plugin  which can manipulate the windows AD.
But I found it can't be installed on linux.

I also found an equivalent python-ldap on linux. 
I can add user by some code  similar with  here:  http://stackoverflow.com/questions/2273117/django-python-ldap-unwilling-to-perform-info-00002077-svcerr-dsid-031907b

However, I found it can only create a user without setting password.

Is there any way I can create a user in windows AD remotely from a linux server  and set the user with the password I want? 

Any suggestion will be  appreciated!!
Thanks!

**Comment by spyoungtech** [comment]
I think you should review the difference between LDAP and Active Directory (Microsoft's ADSI) -- You can almost think of LDAP as a subset of ADSI. They are not equivalents! As far as I know, ADSI is Windows-specific ([see runtime requirements](https://msdn.microsoft.com/en-us/library/aa772170(v=vs.85).aspx)) and there is no unix equivalent or wrapper.

You may use LDAP to interface with your domain, but you won't be able to use ADSI conventions or functionalities. Depending on your needs, python-ldap may be all you need. It is possible to manipulate account passwords with LDAP. I recommend researching the topic more thoroughly.

**Comment by you-n-g** [comment]
Thanks for your advice!
I can use python-ldap do most thing now :)

Post my solution here, Hoping it will help others.

1. following [this tutorial](http://gregtechnobabble.blogspot.com/2012/11/enabling-ldap-ssl-in-windows-2012-part-1.html) to Enable ldaps. Otherwise windows ad will not allow you to do anything related to password.


1. make sure you have this configuration about ldap python-ldap 
ldap.set_option(ldap.OPT_X_TLS_REQUIRE_CERT, ldap.OPT_X_TLS_NEVER)

1. You can follow this post to perform windows AD operations :)
http://marcitland.blogspot.com/2011/02/python-active-directory-linux.html
