### ISSUE TITLE
Can't move user (global name '_adsi_provider' is not defined)

### ISSUE THREAD

**Issue by LeanidN** [zakird/pyad#67]
There is my code (slightly modified:

from pyad import *
user=pyad.aduser.ADUser.from_dn("CN=myname,OU=Production,DC=test,DC=com")
user.move(pyad.adcontainer.ADContainer.from_dn("OU=AutomaticDeactivation,DC=test,DC=com""))

It does move user to new OU but exit with exception:

  File "C:\Python27\lib\site-packages\pyad-0.4.10-py2.7.egg\pyad\adobject.py", line 304, in move
    self._ldap_adsi_obj = _adsi_provider.getObject('',self.__ads_path)
NameError: global name '_adsi_provider' is not defined

From what I understand _adsi_provider is configured in adbase.py and it included in adobject.py, but it is not found by python.
How can I fix it?

**Comment by zakird** [comment]
What version of Python are you running?

**Comment by LeanidN** [comment]
Python 2.7. I realized that I was on old version.
I have updated to the latest pyad code 0.5.16 and same code started to work.
Thanks for quick reply :)
