### ISSUE TITLE
No module named 'adbase'

### ISSUE THREAD

**Issue by revizor1** [zakird/pyad#73]
Python 3.6. 
C:\ProgramData>dir C:\ProgramData\Miniconda3\Lib\site-packages\pyad
 Volume in drive C is Windows

 Directory of C:\ProgramData\Miniconda3\Lib\site-packages\pyad

07/06/2017  09:10 AM    <DIR>          .
07/06/2017  09:10 AM    <DIR>          ..
07/06/2017  09:00 AM             3,427 adbase.py
07/06/2017  09:00 AM               954 adcomputer.py
07/06/2017  09:00 AM             4,010 adcontainer.py
07/06/2017  09:00 AM               722 addomain.py
07/06/2017  09:00 AM             7,824 adgroup.py
07/06/2017  09:00 AM            26,342 adobject.py
07/06/2017  09:00 AM             4,274 adquery.py
07/06/2017  09:00 AM             1,567 adsearch.py
07/06/2017  09:00 AM             1,506 aduser.py
07/06/2017  09:00 AM             1,166 pyad.py
07/06/2017  09:00 AM             6,571 pyadconstants.py
07/06/2017  09:00 AM             2,511 pyadexceptions.py
07/06/2017  09:00 AM             5,894 pyadutils.py
07/06/2017  09:00 AM               178 __init__.py
07/06/2017  09:10 AM    <DIR>          __pycache__
              13 File(s)         66,946 bytes

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-6-28b44198bc9b> in <module>()
----> 1 from pyad import *
      2 user = aduser.ADUser.from_cn("abcd")

C:\ProgramData\Miniconda3\lib\site-packages\pyad\__init__.py in <module>()
----> 1 from adbase import set_defaults as pyad_setdefaults
      2 __all__ = ["adbase", "adquery", "adsearch", "adobject", "adcomputer", "adcontainer", "addomain", "adgroup", "aduser", "pyad"]

ModuleNotFoundError: No module named 'adbase'

**Comment by mrbean-bremen** [comment]
See also https://stackoverflow.com/questions/40004147/pyad-installs-fine-but-says-it-cant-find-adbase.

**Comment by BosnaZmaj** [comment]
Is this issue ever gonna be pushed to pip. It seems as this module has been abandon.

**Comment by zakird** [comment]
I have uploaded a new egg version to pip that represents what's in master.
