### ISSUE TITLE
"Could not find a version that satisfies the requirement pywin32 (from pyad)"

### ISSUE THREAD

**Issue by AlreadyAsleep** [zakird/pyad#75]
I have pywin32-220 installed and am on a Windows 7 64 bit using python 3.6
I tried installing with pip, pip3, and pip3.6... no dice
Have uninstall/reinstalled pywin32 as well as python itself

full dialouge:
`
Could not find a version that satisfies the requirement pywin32 (from pyad) (from versions: )
No matching distribution found for pywin32 (from pyad)
`

**Comment by JamesWaldock** [comment]
[This](https://github.com/zakird/pyad/issues/60#issuecomment-330459480) should help...

**Comment by AlreadyAsleep** [comment]
That did it. Thank you for your help!

**Comment by prashant4737** [comment]
thanks... it worked..

**Comment by KeithSilcock** [comment]
wait what fixed it? I'm having the issue now

**Comment by Karansxa** [comment]
C:\Users\Karan Shah>pip install pywin32
Collecting pywin32
  ERROR: Could not find a version that satisfies the requirement pywin32 (from versions: none)
ERROR: No matching distribution found for pywin32

**Comment by Harjap099** [comment]
> C:\Users\Karan Shah>pip install pywin32
> Collecting pywin32
> ERROR: Could not find a version that satisfies the requirement pywin32 (from versions: none)
> ERROR: No matching distribution found for pywin32

I'm having the same issue. I'm using Ubuntu.

**Comment by Shadow2121** [comment]
` Could not find a version that satisfies the requirement pywin32==228 (from -r /tmp/build_6c2a84a1/requirements.txt (line 56)) (from versions: none)`
i am having this kind of error

**Comment by jithin03** [comment]
Is there any fix for this. I am facing the same issue on macOS.
`ERROR: Could not find a version that satisfies the requirement pywin32==225 (from versions: none)
ERROR: No matching distribution found for pywin32==225`

**Comment by vinsshaji2** [comment]
Please any one can help me to do this
ERROR: Could not find a version that satisfies the requirement pywin32==300 
 ERROR: No matching distribution found for pywin32==300

**Comment by IM-git** [comment]
> Please any one can help me to do this ERROR: Could not find a version that satisfies the requirement pywin32==300 ERROR: No matching distribution found for pywin32==300

Try removing pywin32 in requrements.txt(+after that in my case should have deleted pypiwin32 yet).
