### ISSUE TITLE
ModuleNotFoundError: No Module name 'pyad.adquery';pyad is not a package

### ISSUE THREAD

**Issue by Charannm** [zakird/pyad#81]
import pyad.adquery
q = pyad.adquery.ADQuery()

filename="test.csv"
f=open(filename,"w")
headers="distinguishedName,description,Samaccountname\n"
f.write(headers)

q.execute_query(
    attributes = ["distinguishedName", "description","Samaccountname"],
    where_clause = "objectClass = '*'",
    base_dn = "OU=test, DC=domain, DC=com"
)

for row in q.get_results():
    distinguishedName=(row["distinguishedName"])
    description=(row["description"])
    samaccountname=(row["samaccountname"])
    f.write(distinguishedName+","+ description +","+ samaccountname+"\n")
f.close()

Please find the attached error screenshots and please let me if changes required.

![unnamed](https://user-images.githubusercontent.com/41369559/42876797-72eaf236-8aa5-11e8-967f-996529d5be13.png)

**Comment by makusu2** [comment]
@Charannm You have to import pyad before you import pyad.adquery. Does that work?

**Comment by Charannm** [comment]
its working now and thank you

**Comment by fziae** [comment]
I'm trying to run this 
from pyad import *
from pyad.adcontainer import ADContainer
from pyad.adgroup import ADGroup
from pyad.aduser import ADUser

pyad.set_defaults(ldap_server="10.0.0.131", username="FORWARDLINE\Adminnistrator", password="TkwqV$M*K&e")
ou = ADContainer.from_dn("dc=forwardline, dc=test")
new_user = ADUser.create("Daniel Rec", ou = "Technology", email ="" ,password="Forwardline1")
#group = ADGroup.from_dn("group")

It gives me an error. 

Traceback (most recent call last):
  File "C:/Users/farbod.alizadehziaee/PycharmProjects/untitled/off.py", line 1, in <module>
    from pyad import *
ModuleNotFoundError: No module named 'pyad'

Any ideas?

**Comment by Brito-Antonio** [comment]
@fziae i am getting the same error. where you able to figure this out?
